name: Deploy to GitHub Pages (Alternative)

on:
  workflow_dispatch:  # Permet de déclencher manuellement

permissions:
  contents: write
  actions: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '22.12'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build for GitHub Pages
      run: |
        npm run build:github-pages
        cp dist/recours-ticketing/browser/index.html dist/recours-ticketing/browser/404.html
        echo "" > dist/recours-ticketing/browser/.nojekyll
        
    - name: Create gh-pages branch manually if needed
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        
        # Vérifier si la branche gh-pages existe
        if ! git ls-remote --heads origin gh-pages | grep -q gh-pages; then
          echo "Creating gh-pages branch..."
          git checkout --orphan gh-pages
          git rm -rf .
          echo "GitHub Pages placeholder" > index.html
          git add index.html
          git commit -m "Initial gh-pages commit"
          git push origin gh-pages
          git checkout main
        fi
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist/recours-ticketing/browser
        force_orphan: true
        enable_jekyll: false
